name: terraform

on:
  workflow_call:
    inputs:
      terraform_version:
        type: string
        default: '1.11.1'
      mise_version:
        type: string
        default: '2025.6.8'

jobs:
  setup:
    runs-on: ubuntu-latest
    name: Find changes
    outputs:
      workspaces: ${{ steps.find_changes.outputs.workspaces }}
      environment: ${{ steps.set_environment.outputs.environment }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Find changed workspaces
        id: find_changes
        env:
          BASE_SHA: ${{ github.event.pull_request.base.sha || github.event.before }}
          HEAD_SHA: ${{ github.event.pull_request.head.sha || github.sha }}
        run: |
          set -e -o pipefail
          WORKSPACES=$(git diff $BASE_SHA $HEAD_SHA --diff-filter=ACMR --name-only "*.tf" \
            | { grep -E -v '^templates|modules' || test $? = 1; } \
            | xargs -I{} dirname "{}" \
            | sort | uniq \
            | jq -R -s -c -r 'split("\n")[:-1]')
          echo "workspaces=$WORKSPACES" >> $GITHUB_OUTPUT
      - name: Set environment based on branch
        id: set_environment
        run: |
          if [[ "${GITHUB_REF}" == "refs/heads/main" ]]; then
            echo "environment=deployment" >> $GITHUB_OUTPUT
          else
            echo "environment=read-only" >> $GITHUB_OUTPUT
          fi

  terraform:
    needs: [setup]
    name: Run terraform
    runs-on: ubuntu-latest
    environment: ${{ needs.setup.outputs.environment }}
    env:
      LINODE_TOKEN: ${{ secrets.LINODE_TOKEN }}
      INFISICAL_UNIVERSAL_AUTH_CLIENT_ID: ${{ secrets.INFISICAL_UNIVERSAL_AUTH_CLIENT_ID }}
      INFISICAL_UNIVERSAL_AUTH_CLIENT_SECRET: ${{ secrets.INFISICAL_UNIVERSAL_AUTH_CLIENT_SECRET }}
      AWS_SHARED_CREDENTIALS_FILE: ${{ github.workspace }}/.aws/credentials
      GRAFANA_CLOUD_ACCESS_POLICY_TOKEN: ${{ secrets.GRAFANA_CLOUD_ACCESS_POLICY_TOKEN }}
      GRAFANA_AUTH: ${{ secrets.GRAFANA_AUTH }}
    if: ${{ needs.setup.outputs.workspaces != '[]' }}
    strategy:
      fail-fast: false
      matrix:
        workspace: ${{ fromJson(needs.setup.outputs.workspaces) }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install tools
        uses: jdx/mise-action@v2
        with:
          version: ${{ inputs.mise_version }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tool_versions: |
            terraform ${{ inputs.terraform_version }}
      - name: Write AWS credentials file
        run: |
          mkdir -p $(dirname $AWS_SHARED_CREDENTIALS_FILE)
          echo "${{ secrets.AWS_CREDENTIALS }}" | base64 --decode > $AWS_SHARED_CREDENTIALS_FILE
          chmod 600 $AWS_SHARED_CREDENTIALS_FILE
      - name: Terraform syntax & formatting checks
        run: |
          find ${{ matrix.workspace }} -type f \( -name '*.tf' -o -name '*.tfvars' -o -name '*.tftest.hcl' \) \
            | xargs -n1 terraform fmt -check -diff
      - name: Terraform init
        run: terraform -chdir=${{ matrix.workspace }} init
      - name: Terraform plan
        if: ${{ github.event_name == 'pull_request' && !github.event.pull_request.merged }}
        run: terraform -chdir=${{ matrix.workspace }} plan -lock=false
      - name: Terraform apply
        if: ${{ github.event_name == 'push' && github.ref_name == 'main' }}
        run: terraform -chdir=${{ matrix.workspace }} apply -auto-approve
